/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DrivingApp } from "./DrivingApp";
import { DrivingAppCountArgs } from "./DrivingAppCountArgs";
import { DrivingAppFindManyArgs } from "./DrivingAppFindManyArgs";
import { DrivingAppFindUniqueArgs } from "./DrivingAppFindUniqueArgs";
import { DeleteDrivingAppArgs } from "./DeleteDrivingAppArgs";
import { DrivingAppService } from "../drivingApp.service";
@graphql.Resolver(() => DrivingApp)
export class DrivingAppResolverBase {
  constructor(protected readonly service: DrivingAppService) {}

  async _drivingAppsMeta(
    @graphql.Args() args: DrivingAppCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [DrivingApp])
  async drivingApps(
    @graphql.Args() args: DrivingAppFindManyArgs
  ): Promise<DrivingApp[]> {
    return this.service.drivingApps(args);
  }

  @graphql.Query(() => DrivingApp, { nullable: true })
  async drivingApp(
    @graphql.Args() args: DrivingAppFindUniqueArgs
  ): Promise<DrivingApp | null> {
    const result = await this.service.drivingApp(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DrivingApp)
  async deleteDrivingApp(
    @graphql.Args() args: DeleteDrivingAppArgs
  ): Promise<DrivingApp | null> {
    try {
      return await this.service.deleteDrivingApp(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
