/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DailyIncome } from "./DailyIncome";
import { DailyIncomeCountArgs } from "./DailyIncomeCountArgs";
import { DailyIncomeFindManyArgs } from "./DailyIncomeFindManyArgs";
import { DailyIncomeFindUniqueArgs } from "./DailyIncomeFindUniqueArgs";
import { DeleteDailyIncomeArgs } from "./DeleteDailyIncomeArgs";
import { DailyIncomeService } from "../dailyIncome.service";
@graphql.Resolver(() => DailyIncome)
export class DailyIncomeResolverBase {
  constructor(protected readonly service: DailyIncomeService) {}

  async _dailyIncomesMeta(
    @graphql.Args() args: DailyIncomeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [DailyIncome])
  async dailyIncomes(
    @graphql.Args() args: DailyIncomeFindManyArgs
  ): Promise<DailyIncome[]> {
    return this.service.dailyIncomes(args);
  }

  @graphql.Query(() => DailyIncome, { nullable: true })
  async dailyIncome(
    @graphql.Args() args: DailyIncomeFindUniqueArgs
  ): Promise<DailyIncome | null> {
    const result = await this.service.dailyIncome(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DailyIncome)
  async deleteDailyIncome(
    @graphql.Args() args: DeleteDailyIncomeArgs
  ): Promise<DailyIncome | null> {
    try {
      return await this.service.deleteDailyIncome(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
